using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace RotmgLib.Network.Protocol
{
    public enum Opcode : byte
    {
        FAILURE = 0,
        CREATE_SUCCESS = 1,
        CREATE = 3,
        PLAYERSHOOT = 4,
        MOVE = 5,
        PLAYERTEXT = 6,
        TEXT = 7,
        SHOOT = 8,
        DAMAGE = 9,
        UPDATE = 10,
        MESSAGE = 11,
        NOTIFICATION = 12,
        NEW_TICK = 13,
        INVSWAP = 14,
        USEITEM = 15,
        SHOW_EFFECT = 16,
        HELLO = 17,
        GOTO = 18,
        INVDROP = 19,
        INVRESULT = 20,
        RECONNECT = 21,
        PING = 22,
        PONG = 23,
        MAPINFO = 24,
        LOAD = 25,
        PIC = 26,
        SETCONDITION = 27,
        TELEPORT = 28,
        USEPORTAL = 30,
        DEATH = 31,
        BUY = 33,
        BUYRESULT = 34,
        AOE = 35,
        GROUNDDAMAGE = 36,
        PLAYERHIT = 37,
        ENEMYHIT = 38,
        AOEACK = 39,
        SHOOTACK = 40,
        OTHERHIT = 41,
        SQUAREHIT = 42,
        GOTOACK = 44,
        EDITACCOUNTLIST = 45,
        ACCOUNTLIST = 46,
        QUESTOBJID = 47,
        CHOOSENAME = 48,
        NAMERESULT = 49,
        ALLYSHOOT = 55,
        MULTI_SHOOT = 56,
        REQUESTTRADE = 57,
        TRADEREQUESTED = 58,
        TRADESTART = 59,
        CHANGETRADE = 60,
        TRADECHANGED = 61,
        CHANGEFULLTRADE = 62,
        CANCELTRADE = 63,
        TRADEDONE = 64,
        TRADEACCEPTED = 65,
        CLIENTSTAT = 66,
        CHECKCREDITS = 67,
        ESCAPE = 68
    }
}
